import {
  Accion,
  AgendaEvento,
  BandejaItem,
  Decision,
  Evidencia,
  MovimientoEconomico,
  Persona,
  Proyecto,
} from "./types";

export const SEED_PERSONAS: Persona[] = [
  {
    id: "per-lucia",
    nombre: "Lucía Rangel",
    empresaProyecto: "Casa Norte",
    rol: "Abogada",
    relacion: "Asesora legal externa",
    nivelInfluencia: "Alta",
    intereses: ["Cerrar la operación sin exposición legal para Eduardo"],
    compromisos: ["Confirmar estado del certificado de gravamen"],
    conversacionesPendientes: "Aclarar tema del certificado de gravamen antes de firmar",
    pagosRelacionados: "Honorarios pendientes de facturar al cierre",
    riesgos: ["Podría retrasar la firma si el certificado no se resuelve"],
    ultimoContacto: "2026-07-16",
    proyectoIds: ["proj-casa-norte"],
  },
  {
    id: "per-tomas",
    nombre: "Tomás Ibarra",
    empresaProyecto: "Casa Norte",
    rol: "Vendedor",
    relacion: "Contraparte de negociación",
    nivelInfluencia: "Alta",
    intereses: ["Cerrar rápido a buen precio"],
    compromisos: ["Entregar certificado de gravamen actualizado"],
    conversacionesPendientes: "Sin novedad",
    pagosRelacionados: "Depósito de garantía en curso",
    riesgos: [],
    ultimoContacto: "2026-07-12",
    proyectoIds: ["proj-casa-norte"],
  },
  {
    id: "per-marcos",
    nombre: "Marcos Duarte",
    empresaProyecto: "Estudio Fénix",
    rol: "Cliente ancla",
    relacion: "Socio comercial",
    nivelInfluencia: "Alta",
    intereses: ["Renovar branding con condiciones estables"],
    compromisos: ["Revisar propuesta ajustada"],
    conversacionesPendientes: "Sin novedad",
    pagosRelacionados: "Fee mensual al día",
    riesgos: [],
    ultimoContacto: "2026-07-15",
    proyectoIds: ["proj-fenix"],
  },
  {
    id: "per-renata",
    nombre: "Renata Solis",
    empresaProyecto: "Estudio Fénix",
    rol: "Cliente ancla",
    relacion: "Socia comercial",
    nivelInfluencia: "Media",
    intereses: ["Ampliar alcance del contrato de branding"],
    compromisos: [],
    conversacionesPendientes: "Sin novedad",
    pagosRelacionados: "Fee mensual al día",
    riesgos: [],
    ultimoContacto: "2026-07-10",
    proyectoIds: ["proj-fenix"],
  },
  {
    id: "per-sofia",
    nombre: "Sofía Reyes",
    empresaProyecto: "Fondo Aurora",
    rol: "Gestora de fondo",
    relacion: "Contraparte de inversión",
    nivelInfluencia: "Alta",
    intereses: ["Cerrar ronda con condiciones favorables al fondo"],
    compromisos: ["Enviar term sheet actualizado"],
    conversacionesPendientes: "Responder con lectura del term sheet",
    pagosRelacionados: "N/A",
    riesgos: ["Condiciones de dilución poco claras"],
    ultimoContacto: "2026-07-14",
    proyectoIds: ["proj-aurora"],
  },
  {
    id: "per-andres",
    nombre: "Andrés Palma",
    empresaProyecto: "Fondo Aurora",
    rol: "Analista",
    relacion: "Contraparte de inversión",
    nivelInfluencia: "Media",
    intereses: [],
    compromisos: [],
    conversacionesPendientes: "Sin novedad",
    pagosRelacionados: "N/A",
    riesgos: [],
    ultimoContacto: "2026-07-09",
    proyectoIds: ["proj-aurora"],
  },
  {
    id: "per-ivan",
    nombre: "Iván Castro",
    empresaProyecto: "Contenido Meridian",
    rol: "Productor",
    relacion: "Socio de producción",
    nivelInfluencia: "Alta",
    intereses: ["Avanzar con el documental sin comprometer presupuesto"],
    compromisos: ["Responder sobre el pago vencido"],
    conversacionesPendientes: "Sin respuesta hace 12 días",
    pagosRelacionados: "Pago vencido pendiente de confirmar",
    riesgos: ["Silencio prolongado puede indicar problema de caja de su lado"],
    ultimoContacto: "2026-07-04",
    proyectoIds: ["proj-meridian"],
    diasSinResponder: 12,
  },
];

export const SEED_PROYECTOS: Proyecto[] = [
  {
    id: "proj-fenix",
    nombre: "Estudio Fénix",
    objetivo: "Escalar el estudio de branding a 3 clientes ancla estables",
    ambito: "negocio",
    estado: "Activo",
    prioridad: "Alta",
    personaIds: ["per-marcos", "per-renata"],
    rolUsuario: "Director / propietario",
    situacionEconomica: "Fee mensual recurrente, al día. Renovación en condiciones favorables.",
    proximoHito: "Enviar propuesta ajustada a Bellum — 18 jul",
    riesgos: [],
    oportunidades: ["Ampliar alcance del contrato con Renata Solís"],
    proximaAccionRecomendada: "Avanzar con la renovación del contrato de Bellum",
    evidenceLevel: "verificado",
    creadoEn: "2025-11-02",
  },
  {
    id: "proj-casa-norte",
    nombre: "Casa Norte",
    objetivo: "Adquirir y remodelar propiedad como activo de renta",
    ambito: "negocio",
    estado: "En negociación",
    prioridad: "Alta",
    personaIds: ["per-lucia", "per-tomas"],
    rolUsuario: "Comprador",
    situacionEconomica: "Depósito de garantía en trámite, condicionado a inspección estructural.",
    proximoHito: "Firma de promesa de compraventa — 20 jul · 10:00",
    riesgos: ["Certificado de gravamen sin resolver", "Depósito bloqueado hasta confirmar transferencia"],
    oportunidades: ["Buen punto de entrada como activo de renta"],
    proximaAccionRecomendada: "Condicionar la firma a inspección estructural antes de comprometer el depósito",
    evidenceLevel: "documentado",
    creadoEn: "2026-05-20",
  },
  {
    id: "proj-aurora",
    nombre: "Fondo Aurora",
    objetivo: "Evaluar entrada de capital en fondo semilla",
    ambito: "negocio",
    estado: "En evaluación",
    prioridad: "Media",
    personaIds: ["per-sofia", "per-andres"],
    rolUsuario: "Inversionista potencial",
    situacionEconomica: "Sin compromiso de capital aún. Term sheet en revisión.",
    proximoHito: "Revisar condiciones de dilución del term sheet",
    riesgos: ["Condiciones de dilución actuales pueden no ser favorables"],
    oportunidades: ["Entrada temprana en fondo semilla"],
    proximaAccionRecomendada: "Pedir aclaración de dilución antes de comprometer capital",
    evidenceLevel: "reportado",
    creadoEn: "2026-06-30",
  },
  {
    id: "proj-meridian",
    nombre: "Contenido Meridian",
    estado: "En negociación",
    ambito: "negocio",
    objetivo: "Lanzar serie documental con Meridian Studios",
    prioridad: "Alta",
    personaIds: ["per-ivan"],
    rolUsuario: "Productor ejecutivo",
    situacionEconomica: "Pago vencido sin conciliar. Sin respuesta de la contraparte.",
    proximoHito: "Definir si se escala o se pausa el proyecto",
    riesgos: ["12 días sin respuesta de Iván Castro", "Pago vencido sin confirmar"],
    oportunidades: [],
    proximaAccionRecomendada: "Escalar el reclamo de pago o pausar el proyecto",
    evidenceLevel: "reportado",
    creadoEn: "2026-04-18",
  },
  {
    id: "proj-vega",
    nombre: "Consultoría Vega",
    objetivo: "Diagnóstico operativo y recomendaciones de eficiencia para Vega",
    ambito: "negocio",
    estado: "Cerrado",
    prioridad: "Baja",
    personaIds: [],
    rolUsuario: "Consultor",
    situacionEconomica: "Facturación completa y cobrada.",
    proximoHito: "Sin próximos hitos — proyecto cerrado",
    riesgos: [],
    oportunidades: [],
    proximaAccionRecomendada: "Ninguna — proyecto cerrado",
    evidenceLevel: "verificado",
    creadoEn: "2026-01-15",
  },
];

export const SEED_ACCIONES: Accion[] = [
  {
    id: "acc-bellum",
    titulo: "Enviar propuesta ajustada a Bellum",
    resultadoEsperado: "Propuesta revisada enviada y en espera de confirmación",
    proyectoId: "proj-fenix",
    responsable: "Eduardo",
    prioridad: "P2",
    estado: "En curso",
    fecha: "2026-07-18",
    duracionEstimada: "45 min",
    dependencias: "Ninguna",
    impactoFinanciero: "Renovación de fee mensual ~$5M",
    evidenciaCierre: "",
    creadoEn: "2026-07-12",
  },
  {
    id: "acc-garantia",
    titulo: "Revisar cláusula de garantía con Lucía",
    resultadoEsperado: "Cláusula de garantía validada antes de firmar",
    proyectoId: "proj-casa-norte",
    responsable: "Eduardo",
    prioridad: "P1",
    estado: "Pendiente",
    fecha: "2026-07-17",
    duracionEstimada: "30 min",
    dependencias: "Certificado de gravamen resuelto",
    impactoFinanciero: "Protege el depósito de garantía",
    evidenciaCierre: "",
    creadoEn: "2026-07-14",
  },
  {
    id: "acc-transferencia",
    titulo: "Confirmar transferencia de depósito",
    resultadoEsperado: "Depósito confirmado y registrado",
    proyectoId: "proj-casa-norte",
    responsable: "Eduardo",
    prioridad: "P1",
    estado: "Bloqueada",
    fecha: "2026-07-20",
    duracionEstimada: "15 min",
    dependencias: "Firma de promesa de compraventa",
    impactoFinanciero: "Movimiento de caja significativo",
    evidenciaCierre: "",
    creadoEn: "2026-07-10",
  },
  {
    id: "acc-seguimiento-meridian",
    titulo: "Dar seguimiento a pago vencido",
    resultadoEsperado: "Respuesta de Iván Castro sobre el pago",
    proyectoId: "proj-meridian",
    responsable: "Eduardo",
    prioridad: "P2",
    estado: "Esperando tercero",
    fecha: "2026-07-15",
    duracionEstimada: "10 min",
    dependencias: "Ninguna",
    impactoFinanciero: "Pago vencido pendiente de cobrar",
    evidenciaCierre: "",
    creadoEn: "2026-07-04",
  },
];

export const SEED_DECISIONES: Decision[] = [
  {
    id: "dec-casa-norte",
    pregunta: "¿Firmar la promesa de compraventa de Casa Norte en estos términos?",
    contexto:
      "Lucía reportó un tema pendiente con el certificado de gravamen. El depósito de garantía está listo pero condicionado.",
    proyectoId: "proj-casa-norte",
    fechaLimite: "2026-07-20",
    nivelRiesgo: "Alto",
    evidenceLevel: "documentado",
    opciones: ["Firmar ya", "Firmar condicionado a inspección", "Esperar certificado de gravamen"],
    escenarios: [
      { tipo: "avanzar", analisis: "Firmar ahora asegura el precio pero expone a riesgo legal si el gravamen no se resuelve." },
      { tipo: "avanzar_condicionado", analisis: "Firmar condicionando la promesa a una inspección estructural y a la resolución del gravamen protege el depósito." },
      { tipo: "probar", analisis: "No aplica de forma directa — la operación es binaria (se compra o no)." },
      { tipo: "renegociar", analisis: "Pedir a Tomás una extensión de 5-7 días para resolver el certificado sin perder el precio pactado." },
      { tipo: "esperar", analisis: "Esperar el certificado de gravamen cuesta días de ventana, pero evita comprometer capital con un riesgo legal abierto." },
      { tipo: "pausar", analisis: "Pausar protege el depósito pero puede hacer perder la propiedad si Tomás tiene otro comprador." },
      { tipo: "salir", analisis: "Salir ahora tiene bajo costo (solo tiempo invertido), pero pierde una oportunidad de buen activo de renta." },
      { tipo: "no_hacer_nada", analisis: "No decidir antes del 20 jul implica perder la ventana de firma y probablemente el precio pactado." },
    ],
    impactoEconomico: "Depósito de garantía + costo de remodelación estimado",
    recomendacionSistema: "Condicionar a inspección estructural antes de firmar",
    decisionFinal: "",
    condiciones: ["Certificado de gravamen resuelto", "Inspección estructural favorable"],
    resultadoPosterior: "",
    estado: "Abierta",
    creadoEn: "2026-07-14",
  },
  {
    id: "dec-aurora",
    pregunta: "¿Aceptar la entrada de Fondo Aurora con las condiciones actuales de dilución?",
    contexto: "Sofía envió el term sheet actualizado. Las condiciones de dilución no están del todo claras.",
    proyectoId: "proj-aurora",
    fechaLimite: "2026-07-29",
    nivelRiesgo: "Medio",
    evidenceLevel: "reportado",
    opciones: ["Aceptar", "Renegociar dilución", "Rechazar"],
    escenarios: [
      { tipo: "avanzar", analisis: "Aceptar ahora asegura la entrada temprana en el fondo semilla." },
      { tipo: "avanzar_condicionado", analisis: "Aceptar condicionado a una cláusula anti-dilución para rondas futuras." },
      { tipo: "probar", analisis: "Solicitar una entrada parcial para validar el fondo con menor exposición." },
      { tipo: "renegociar", analisis: "Pedir a Sofía aclarar y ajustar los términos de dilución antes de comprometer capital." },
      { tipo: "esperar", analisis: "Esperar más información sobre el desempeño del fondo antes de decidir." },
      { tipo: "pausar", analisis: "Pausar la evaluación no tiene costo alto — el fondo sigue abierto para otros inversionistas." },
      { tipo: "salir", analisis: "Rechazar preserva capital pero cierra la oportunidad de entrada temprana." },
      { tipo: "no_hacer_nada", analisis: "No decidir antes del 29 jul probablemente cierra la ventana de esta ronda." },
    ],
    impactoEconomico: "Compromiso de capital en fondo semilla",
    recomendacionSistema: "Pedir aclaración de dilución antes de comprometer capital",
    decisionFinal: "",
    condiciones: ["Términos de dilución aclarados por escrito"],
    resultadoPosterior: "",
    estado: "Abierta",
    creadoEn: "2026-07-14",
  },
];

export const SEED_MOVIMIENTOS: MovimientoEconomico[] = [
  {
    id: "mov-fenix-pago",
    tipo: "ingreso",
    monto: 3200,
    moneda: "USD",
    fecha: "2026-07-14",
    proyectoId: "proj-fenix",
    descripcion: "Pago de Estudio Fénix",
    estado: "confirmado",
    fuente: "Transferencia bancaria",
    cuenta: "BoA USD",
  },
  {
    id: "mov-meridian-vencido",
    tipo: "ingreso",
    monto: 1800,
    moneda: "USD",
    fecha: "2026-07-04",
    proyectoId: "proj-meridian",
    descripcion: "Pago vencido — Contenido Meridian",
    estado: "sin_conciliar",
    fuente: "Reportado por Eduardo",
    cuenta: "BoA USD",
  },
  {
    id: "mov-casa-norte-deposito",
    tipo: "gasto",
    monto: 45000,
    moneda: "USD",
    fecha: "2026-07-20",
    proyectoId: "proj-casa-norte",
    descripcion: "Depósito de garantía Casa Norte",
    estado: "esperado",
    fuente: "Promesa de compraventa",
    cuenta: "Cuenta ahorros Casa Norte",
  },
  {
    id: "mov-vega-cierre",
    tipo: "ingreso",
    monto: 6000,
    moneda: "USD",
    fecha: "2026-06-20",
    proyectoId: "proj-vega",
    descripcion: "Facturación final Consultoría Vega",
    estado: "confirmado",
    fuente: "Transferencia bancaria",
    cuenta: "BoA USD",
  },
];

export const SEED_EVIDENCIAS: Evidencia[] = [
  {
    id: "ev-fenix-comprobante",
    tipo: "comprobante",
    fuente: "Banco — comprobante de transferencia",
    fecha: "2026-07-14",
    proyectoId: "proj-fenix",
    nivelConfiabilidad: "verificado",
    afirmacionRespaldada: "Pago de $3,200 recibido de Estudio Fénix",
    estadoVerificacion: "verificada",
  },
  {
    id: "ev-casa-norte-gravamen",
    tipo: "correo",
    fuente: "Correo de Lucía Rangel",
    fecha: "2026-07-16",
    proyectoId: "proj-casa-norte",
    nivelConfiabilidad: "reportado",
    afirmacionRespaldada: "Existe un tema pendiente con el certificado de gravamen",
    estadoVerificacion: "pendiente",
  },
  {
    id: "ev-aurora-termsheet",
    tipo: "propuesta",
    fuente: "Documento compartido por Sofía Reyes",
    fecha: "2026-07-14",
    proyectoId: "proj-aurora",
    nivelConfiabilidad: "documentado",
    afirmacionRespaldada: "Term sheet actualizado con condiciones de dilución",
    estadoVerificacion: "pendiente",
  },
];

export const SEED_BANDEJA: BandejaItem[] = [
  {
    id: "bnd-fenix-pago",
    texto: "Recibí el pago de $3,200 de Estudio Fénix",
    fecha: "2026-07-14",
    estado: "Procesado",
    clasificacion: {
      destino: "economia",
      proyectoId: "proj-fenix",
      confianza: 0.95,
      razon: "Movimiento económico — ingreso confirmado",
    },
    resultadoLabel: "Movimiento económico — Ingreso confirmado",
  },
  {
    id: "bnd-casa-norte-gravamen",
    texto: "Lucía dice que hay un tema con el certificado de gravamen",
    fecha: "2026-07-16",
    estado: "Necesita confirmación",
    clasificacion: {
      destino: "evidencia",
      proyectoId: "proj-casa-norte",
      confianza: 0.62,
      razon: "Riesgo — vinculado a Casa Norte, requiere evidencia",
    },
  },
  {
    id: "bnd-aurora-termsheet",
    texto: "Sofía me mandó el term sheet actualizado",
    fecha: "2026-07-14",
    estado: "En análisis",
    clasificacion: {
      destino: "evidencia",
      proyectoId: "proj-aurora",
      confianza: 0.7,
      razon: "Evidencia — documento de respaldo para decisión de inversión",
    },
  },
  {
    id: "bnd-meridian-silencio",
    texto: "Iván sigue sin responder sobre el pago vencido de Contenido Meridian",
    fecha: "2026-07-16",
    estado: "Nuevo",
    clasificacion: {
      destino: "decision",
      proyectoId: "proj-meridian",
      confianza: 0.55,
      razon: "Patrón de riesgo relacional — posible necesidad de escalar o pausar",
    },
  },
];

export const SEED_AGENDA: AgendaEvento[] = [
  {
    id: "evt-casa-norte-firma",
    titulo: "Firma de promesa de compraventa",
    fecha: "2026-07-20",
    hora: "10:00",
    proyectoId: "proj-casa-norte",
    descripcion: "Firma condicionada a inspección estructural",
    tipo: "Compromiso legal",
  },
  {
    id: "evt-fenix-reunion",
    titulo: "Reunión de seguimiento con Marcos",
    fecha: "2026-07-19",
    hora: "16:00",
    proyectoId: "proj-fenix",
    descripcion: "Revisar propuesta ajustada para Bellum",
    tipo: "Reunión",
  },
];
