import { VincereProyecto, VincereTriageCaso } from "./types";

// Caso real de arranque (SETTE) + una referencia de competencia (LUNA REBEL)
// cargada manualmente — mismos números validados en el prototipo de Eduardo,
// para que la plataforma abra ya poblada con el primer diagnóstico real.
export const SEED_VINCERE_PROYECTOS: VincereProyecto[] = [
  {
    id: "vin-sette",
    nombre: "SETTE",
    genero: "Pop urbano",
    fase: "Emergente → Consolidación",
    tipo: "propio",
    creadoEn: "2026-01-15",
    resumen: {
      streamsMes: 2430000,
      streamsCambioPct: 18,
      seguidores: 186000,
      seguidoresCambioPct: 6,
      momentumIndex: 62,
      serie: [
        { mes: "Feb", valor: 1450 },
        { mes: "Mar", valor: 1610 },
        { mes: "Abr", valor: 1780 },
        { mes: "May", valor: 1920 },
        { mes: "Jun", valor: 2100 },
        { mes: "Jul", valor: 2430 },
      ],
    },
    diagnostico: {
      faseActual: "Emergente, entrando a Consolidación",
      fortalezaNucleo: "Retención de audiencia en temas de tempo medio",
      riesgoPrincipal: "Dependencia de un solo tema para el 40% del streaming activo",
      prioridad: "Diversificar catálogo con al menos 2 lanzamientos en el próximo trimestre",
    },
    canciones: [
      { id: "song-1", nombre: "Bajo Cero", streams: 890000, retencionPct: 68, skipPct: 22, playlistAdds: 340 },
      { id: "song-2", nombre: "Nadie Como Tú", streams: 640000, retencionPct: 74, skipPct: 15, playlistAdds: 510 },
      { id: "song-3", nombre: "Fuego Lento", streams: 410000, retencionPct: 58, skipPct: 31, playlistAdds: 120 },
      { id: "song-4", nombre: "Otra Vida", streams: 310000, retencionPct: 81, skipPct: 9, playlistAdds: 690 },
      { id: "song-5", nombre: "Sin Aviso", streams: 180000, retencionPct: 45, skipPct: 40, playlistAdds: 40 },
    ],
    audiencia: {
      edad: [
        { label: "18–24", pct: 38 },
        { label: "25–34", pct: 31 },
        { label: "35–44", pct: 17 },
        { label: "45+", pct: 14 },
      ],
      plataformas: [
        { label: "Spotify", pct: 54 },
        { label: "YouTube", pct: 24 },
        { label: "TikTok", pct: 16 },
        { label: "Otros", pct: 6 },
      ],
      paises: [
        { label: "México", pct: 42 },
        { label: "Colombia", pct: 18 },
        { label: "España", pct: 12 },
        { label: "EE.UU.", pct: 11 },
        { label: "Argentina", pct: 9 },
        { label: "Otros", pct: 8 },
      ],
    },
    zonasCalor: [
      { id: "city-1", ciudad: "Ciudad de México", calor: 92 },
      { id: "city-2", ciudad: "Guadalajara", calor: 78 },
      { id: "city-3", ciudad: "Bogotá", calor: 71 },
      { id: "city-4", ciudad: "Monterrey", calor: 65 },
      { id: "city-5", ciudad: "Madrid", calor: 58 },
      { id: "city-6", ciudad: "Buenos Aires", calor: 44 },
      { id: "city-7", ciudad: "Miami", calor: 39 },
    ],
    decisiones: [
      { id: "dec-1", texto: "Lanzar EP en octubre vs diciembre", estado: "Pendiente", creadoEn: "2026-07-01" },
      { id: "dec-2", texto: "Firmar con booking agency regional", estado: "Pendiente", creadoEn: "2026-07-05" },
      {
        id: "dec-3",
        texto: "Rechazar feature con artista de bajo fit de marca",
        estado: "Tomada",
        creadoEn: "2026-06-18",
      },
      {
        id: "dec-4",
        texto: "Aumentar frecuencia de contenido corto (Reels/TikTok)",
        estado: "Tomada",
        creadoEn: "2026-06-02",
      },
    ],
    kpis: [
      { id: "kpi-1", label: "Streams mensuales", actual: 2.43, meta: 3, unidad: "M", nota: "81% de la meta trimestral" },
      {
        id: "kpi-2",
        label: "Shows confirmados (trimestre)",
        actual: 4,
        meta: 6,
        unidad: "",
        nota: "67% — dos por confirmar",
      },
      { id: "kpi-3", label: "Playlist editorial adds", actual: 3, meta: 5, unidad: "", nota: "60% de la meta" },
      {
        id: "kpi-4",
        label: "Presupuesto marketing usado",
        actual: 72,
        meta: 100,
        unidad: "%",
        nota: "72% del gasto con solo 40% del trimestre transcurrido — ritmo adelantado",
      },
    ],
    insights: {},
    qaLog: {},
  },
  {
    id: "vin-luna-rebel",
    nombre: "LUNA REBEL",
    genero: "Pop urbano",
    fase: "Consolidación",
    tipo: "competencia",
    creadoEn: "2026-07-10",
    resumen: {
      streamsMes: 1800000,
      streamsCambioPct: 4,
      seguidores: 240000,
      seguidoresCambioPct: 2,
      momentumIndex: 71,
      serie: [
        { mes: "Feb", valor: 1620 },
        { mes: "Mar", valor: 1660 },
        { mes: "Abr", valor: 1700 },
        { mes: "May", valor: 1740 },
        { mes: "Jun", valor: 1770 },
        { mes: "Jul", valor: 1800 },
      ],
    },
    diagnostico: {
      faseActual: "Consolidación",
      fortalezaNucleo: "Base de fans consolidada, catálogo profundo",
      riesgoPrincipal: "Crecimiento desacelerado frente a artistas emergentes",
      prioridad: "Sostener relevancia con lanzamientos de mayor frecuencia",
    },
    canciones: [],
    audiencia: { edad: [], plataformas: [], paises: [] },
    zonasCalor: [],
    decisiones: [],
    kpis: [],
    insights: {},
    qaLog: {},
  },
];

export const SEED_VINCERE_TRIAGE: VincereTriageCaso[] = [];
